CREATE DATABASE [milennial_dev]  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S1', MAXSIZE = 250 GB);

GO
ALTER DATABASE [milennial_dev] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [milennial_dev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [milennial_dev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [milennial_dev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [milennial_dev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [milennial_dev] SET ARITHABORT OFF 
GO
ALTER DATABASE [milennial_dev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [milennial_dev] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [milennial_dev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [milennial_dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [milennial_dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [milennial_dev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [milennial_dev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [milennial_dev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [milennial_dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [milennial_dev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [milennial_dev] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [milennial_dev] SET  READ_WRITE 
GO
ALTER DATABASE [milennial_dev] SET  MULTI_USER 
GO
ALTER DATABASE [milennial_dev] SET ENCRYPTION ON
GO
/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
-- ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
